### ISSUE TITLE
Get Clipboard working in Linux

### ISSUE THREAD

**Issue by Daniel-Diaz** [Daniel-Diaz/Clipboard#1]
This library has always worked nicely in Windows systems. It's time to make it work in Linux too.

**Comment by mat8913** [comment]
I started working on this [here](https://github.com/mat8913/Clipboard/tree/x11). I've finished getClipboardString and will hopefully have setClipboardString done by the end of today. The module no longer exports `cF_UNICODETEXT` as there doesn't seem to be an X11 equivalent.

**Comment by Daniel-Diaz** [comment]
Thanks! That's great! This issue has been opened for more than 2 years now.
